export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCEED = 'CREATE_CATEGORY_SUCCEED';
export const CREATE_CATEGORY_FAILED = 'CREATE_CATEGORY_FAILED';

export const GET_LIST_CATE = 'GET_LIST_CATE'
export const GET_LIST_CATE_SUCCESS = 'GET_LIST_CATE_SUCCESS'