export const FETCH_USER_BALANCES = 'FETCH_USER_BALANCES';
export const FETCH_USER_BALANCES_SUCCEED = 'FETCH_USER_BALANCES_SUCCEED';
export const FETCH_USER_BALANCES_FAILED = 'FETCH_USER_BALANCES_FAILED';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const GET_PERMISSION = 'GET_PERMISSION'
export const GET_PERMISSION_SUCCESS = 'GET_PERMISSION_SUCCESS'
